/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package link.hiroshisprojects.hibernate;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import link.hiroshisprojects.hibernate.item.Item;
import link.hiroshisprojects.hibernate.order.PurchaseOrder;


public class App {

	private static final EntityManagerFactory emf = Persistence.createEntityManagerFactory("MyPersistenceUnit");
	private static final Logger LOGGER = LoggerFactory.getLogger(App.class);
	public static void main(String[] args) {
	
		EntityManager entityManager = emf.createEntityManager();

		Item shoes = new Item("shoes", 10.50);
		Set<Item> items = new HashSet<>();
		items.add(shoes);

		PurchaseOrder order = new PurchaseOrder();
		order.addItem(shoes);

		entityManager.getTransaction().begin();
		entityManager.persist(order);
		entityManager.getTransaction().commit();
    }
}
